[package]
name = "rube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chomp1 = "0.3.4"
derive-new = "0.6.0"
lazy_static = "1.4.0"
static_assertions = "1.1.0"
strum = "0.26"
strum_macros = "0.26"
